{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-disk.frame
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/disk.frame_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/disk.frame/disk.frame_{{ version }}.tar.gz
  sha256: bc951195fa6eca6170ac7c16f04e8ccb03bbfee7429e15214134f612867395fc

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.13
    - r-benchmarkme
    - r-bigreadr >=0.2.0
    - r-bit64
    - r-crayon >=1.3.4
    - r-data.table >=1.12.2
    - r-dplyr >=1.0.0
    - r-fs >=1.3.1
    - r-fst >=0.8.0
    - r-furrr >=0.1.0
    - r-future >=1.14.0
    - r-future.apply >=1.3.0
    - r-globals >=0.12.4
    - r-glue >=1.3.1
    - r-jsonlite >=1.6
    - r-pryr >=0.1.4
    - r-purrr >=0.3.2
    - r-rlang >=0.4.0
    - r-stringr >=1.4.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.13
    - r-benchmarkme
    - r-bigreadr >=0.2.0
    - r-bit64
    - r-crayon >=1.3.4
    - r-data.table >=1.12.2
    - r-dplyr >=1.0.0
    - r-fs >=1.3.1
    - r-fst >=0.8.0
    - r-furrr >=0.1.0
    - r-future >=1.14.0
    - r-future.apply >=1.3.0
    - r-globals >=0.12.4
    - r-glue >=1.3.1
    - r-jsonlite >=1.6
    - r-pryr >=0.1.4
    - r-purrr >=0.3.2
    - r-rlang >=0.4.0
    - r-stringr >=1.4.0

test:
  commands:
    - $R -e "library('disk.frame')"           # [not win]
    - "\"%R%\" -e \"library('disk.frame')\""  # [win]

about:
  home: https://diskframe.com
  license: MIT
  summary: A disk-based data manipulation tool for working with large-than-RAM datasets. Aims to lower the barrier-to-entry for manipulating large datasets by adhering closely to popular and familiar data manipulation paradigms like dplyr verbs and data.table syntax.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf
    - xiaodaigh

# Type: Package
# Package: disk.frame
# Title: Larger-than-RAM Disk-Based Data Manipulation Framework
# Version: 0.3.7
# Date: 2020-07-07
# Authors@R: c( person("Dai", "ZJ", email = "zhuojia.dai@gmail.com", role = c("aut", "cre")), person("Jacky", "Poon", role = c("ctb")) )
# Maintainer: Dai ZJ <zhuojia.dai@gmail.com>
# Description: A disk-based data manipulation tool for working with large-than-RAM datasets. Aims to lower the barrier-to-entry for manipulating large datasets by adhering closely to popular and familiar data manipulation paradigms like 'dplyr' verbs and 'data.table' syntax.
# License: MIT + file LICENSE
# Imports: Rcpp (>= 0.12.13), glue (>= 1.3.1), rlang (>= 0.4.0), furrr (>= 0.1.0), future.apply (>= 1.3.0), fs (>= 1.3.1), jsonlite (>= 1.6), pryr (>= 0.1.4), stringr (>= 1.4.0), fst (>= 0.8.0), globals (>= 0.12.4), future (>= 1.14.0), data.table (>= 1.12.2), crayon (>= 1.3.4), bigreadr (>= 0.2.0), bit64, benchmarkme
# Depends: R (>= 3.4), dplyr (>= 1.0.0), purrr (>= 0.3.2)
# Suggests: testthat (>= 2.1.0), nycflights13, magrittr, shiny, LaF, readr, rstudioapi, biglm, biglmm, speedglm, broom, ggplot2, covr
# LinkingTo: Rcpp
# RoxygenNote: 7.1.0
# Encoding: UTF-8
# URL: https://diskframe.com
# BugReports: https://github.com/xiaodaigh/disk.frame/issues
# NeedsCompilation: yes
# Packaged: 2020-07-07 09:16:14 UTC; RTX2080
# Author: Dai ZJ [aut, cre], Jacky Poon [ctb]
# Repository: CRAN
# Date/Publication: 2020-07-07 13:10:03 UTC
